import type { Metadata } from "next";
import { Inter} from "next/font/google";
import "./globals.css";
import ResponsiveNav from "@/components/Home/Navbar/ResponsiveNav";

const font = Inter({
  weight:["100","200","300","400","500","600","700","800","900"],
  subsets:["latin"],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Ravi Agrahari - Portfolio|Full Stack Developer",
  description: "Generated by create next app",
  keywords: ["Ravi Agrahari", "Full Stack Developer", "Portfolio", "Web Development", "React", "Next.js", "Tailwind CSS", "TypeScript", "JavaScript", "HTML", "CSS"],
  authors: [{ name: "Ravi Agrahari", url: "https://raviagrahari.com" }],
  creator: "Ravi Agrahari",
  publisher: "Ravi Agrahari",
  openGraph: {
    title: "Ravi Agrahari - Portfolio|Full Stack Developer",
    description: "Generated by create next app",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased bg-[#0d0d1f]`}
      >
        <ResponsiveNav />
        {children}
      </body>
    </html>
  );
}
